version: '3.4'

services:
  storage-api:
    image: storage-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - storage-postgres
    restart: unless-stopped
  storage-postgres:
    image: postgres
    env_file:
      - deployment/local/.env
    ports:
      - "5433:5432"
    volumes:
      - pg-volume:/var/lib/postgresql/data
volumes:
  pg-volume:
